/** Países (nombres en español) para selectores de origen. */
export const PAISES = [
  "Afganistán",
  "Albania",
  "Alemania",
  "Andorra",
  "Angola",
  "Antigua y Barbuda",
  "Arabia Saudita",
  "Argelia",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaiyán",
  "Bahamas",
  "Bangladés",
  "Barbados",
  "Baréin",
  "Bélgica",
  "Belice",
  "Benín",
  "Bielorrusia",
  "Birmania",
  "Bolivia",
  "Bosnia y Herzegovina",
  "Botsuana",
  "Brasil",
  "Brunéi",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Bután",
  "Cabo Verde",
  "Camboya",
  "Camerún",
  "Canadá",
  "Catar",
  "Chad",
  "Chile",
  "China",
  "Chipre",
  "Ciudad del Vaticano",
  "Colombia",
  "Comoras",
  "Congo",
  "Corea del Norte",
  "Corea del Sur",
  "Costa de Marfil",
  "Costa Rica",
  "Croacia",
  "Cuba",
  "Dinamarca",
  "Dominica",
  "Ecuador",
  "Egipto",
  "El Salvador",
  "Emiratos Árabes Unidos",
  "Eritrea",
  "Eslovaquia",
  "Eslovenia",
  "España",
  "Estados Unidos",
  "Estonia",
  "Esuatini",
  "Etiopía",
  "Filipinas",
  "Finlandia",
  "Fiyi",
  "Francia",
  "Gabón",
  "Gambia",
  "Georgia",
  "Ghana",
  "Granada",
  "Grecia",
  "Guatemala",
  "Guinea",
  "Guinea-Bisáu",
  "Guinea Ecuatorial",
  "Guyana",
  "Haití",
  "Honduras",
  "Hungría",
  "India",
  "Indonesia",
  "Irak",
  "Irán",
  "Irlanda",
  "Islandia",
  "Islas Marshall",
  "Islas Salomón",
  "Israel",
  "Italia",
  "Jamaica",
  "Japón",
  "Jordania",
  "Kazajistán",
  "Kenia",
  "Kirguistán",
  "Kiribati",
  "Kuwait",
  "Laos",
  "Lesoto",
  "Letonia",
  "Líbano",
  "Liberia",
  "Libia",
  "Liechtenstein",
  "Lituania",
  "Luxemburgo",
  "Macedonia del Norte",
  "Madagascar",
  "Malasia",
  "Malaui",
  "Maldivas",
  "Malí",
  "Malta",
  "Marruecos",
  "Mauricio",
  "Mauritania",
  "México",
  "Micronesia",
  "Moldavia",
  "Mónaco",
  "Mongolia",
  "Montenegro",
  "Mozambique",
  "Namibia",
  "Nauru",
  "Nepal",
  "Nicaragua",
  "Níger",
  "Nigeria",
  "Noruega",
  "Nueva Zelanda",
  "Omán",
  "Países Bajos",
  "Pakistán",
  "Palaos",
  "Palestina",
  "Panamá",
  "Papúa Nueva Guinea",
  "Paraguay",
  "Perú",
  "Polonia",
  "Portugal",
  "Reino Unido",
  "República Centroafricana",
  "República Checa",
  "República Democrática del Congo",
  "República Dominicana",
  "Ruanda",
  "Rumania",
  "Rusia",
  "Samoa",
  "San Cristóbal y Nieves",
  "San Marino",
  "San Vicente y las Granadinas",
  "Santa Lucía",
  "Santo Tomé y Príncipe",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leona",
  "Singapur",
  "Siria",
  "Somalia",
  "Sri Lanka",
  "Sudáfrica",
  "Sudán",
  "Sudán del Sur",
  "Suecia",
  "Suiza",
  "Surinam",
  "Tailandia",
  "Taiwán",
  "Tanzania",
  "Tayikistán",
  "Timor Oriental",
  "Togo",
  "Tonga",
  "Trinidad y Tobago",
  "Túnez",
  "Turkmenistán",
  "Turquía",
  "Tuvalu",
  "Ucrania",
  "Uganda",
  "Uruguay",
  "Uzbekistán",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Yibuti",
  "Zambia",
  "Zimbabue",
] as const;

export type Pais = (typeof PAISES)[number];

const PAIS_ALIASES: Record<string, Pais> = {
  china: "China",
  prc: "China",
  "p.r.c": "China",
  "p.r.c.": "China",
  "p.r. china": "China",
  "p.r.china": "China",
  "pr china": "China",
  "p r china": "China",
  "the peoples republic of china": "China",
  "peoples republic of china": "China",
  "mainland china": "China",
  "republic of china": "Taiwán",
  usa: "Estados Unidos",
  us: "Estados Unidos",
  "united states": "Estados Unidos",
  "united states of america": "Estados Unidos",
  "eeuu": "Estados Unidos",
  "ee.uu.": "Estados Unidos",
  "ee. uu.": "Estados Unidos",
  japan: "Japón",
  korea: "Corea del Sur",
  "south korea": "Corea del Sur",
  "north korea": "Corea del Norte",
  germany: "Alemania",
  france: "Francia",
  spain: "España",
  italy: "Italia",
  brazil: "Brasil",
  mexico: "México",
  "south africa": "Sudáfrica",
  uk: "Reino Unido",
  "united kingdom": "Reino Unido",
  england: "Reino Unido",
  netherlands: "Países Bajos",
  holland: "Países Bajos",
  russia: "Rusia",
  turkey: "Turquía",
  uae: "Emiratos Árabes Unidos",
  "united arab emirates": "Emiratos Árabes Unidos",
  vietnam: "Vietnam",
  "viet nam": "Vietnam",
  india: "India",
  thailand: "Tailandia",
  indonesia: "Indonesia",
  malaysia: "Malasia",
  singapore: "Singapur",
  taiwan: "Taiwán",
  colombia: "Colombia",
  panama: "Panamá",
  peru: "Perú",
  chile: "Chile",
  argentina: "Argentina",
  canada: "Canadá",
};

function normalizeKey(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .normalize("NFD")
    .replace(/\p{M}/gu, "")
    .replace(/['’`]/g, "")
    .replace(/\s+/g, " ");
}

/** Resuelve texto libre (OCR / inglés) al nombre del catálogo cuando es posible. */
export function resolvePais(value: string | null | undefined): string {
  const raw = value?.trim() ?? "";
  if (!raw) return "";
  const exact = PAISES.find((p) => p.toLowerCase() === raw.toLowerCase());
  if (exact) return exact;
  const alias = PAIS_ALIASES[normalizeKey(raw)];
  if (alias) return alias;
  const partial = PAISES.find((p) => normalizeKey(p) === normalizeKey(raw));
  return partial ?? raw;
}

/** Como `resolvePais`, pero solo si cae en el catálogo (ignora basura OCR). */
export function resolvePaisCatalog(
  value: string | null | undefined
): string | null {
  const resolved = resolvePais(value);
  if (!resolved) return null;
  return (PAISES as readonly string[]).includes(resolved) ? resolved : null;
}
